# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon:
open_collective:
ko_fi: 5argon
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://assetstore.unity.com/publishers/18007
